name: Haneda Parking Check

on:
  schedule:
    - cron: "*/5 * * * *"   # 5分ごと
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python check.py
